version: '3'

volumes:
  mariadb:

networks:
  fleet-preview:
    name: fleet-preview

services:
  mariadb:
    container_name: fleet-mariadb
    image: mariadb
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - mariadb:/var/lib/mysqld
    networks:
      - fleet-preview

  redis:
    container_name: fleet-redis
    image: redis:6
    networks:
      - fleet-preview

  fleet:
    container_name: fleet
    image: fleetdm/fleet:latest
    command: sh -c "/usr/bin/fleet prepare db --no-prompt && /usr/bin/fleet serve"
    environment:
      FLEET_MYSQL_ADDRESS: mariadb:3306
      FLEET_MYSQL_DATABASE: "${MYSQL_DATABASE}"
      FLEET_MYSQL_USERNAME: "${MYSQL_USER}"
      FLEET_MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      FLEET_REDIS_ADDRESS: redis:6379
      FLEET_SERVER_ADDRESS: 0.0.0.0:8412
      FLEET_SERVER_CERT: /fleet/ssl/fleet.crt
      FLEET_SERVER_KEY: /fleet/ssl/fleet.key
      FLEET_LOGGING_JSON: "true"
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./ssl/:/fleet/ssl/
      - ./options.yaml:/fleet/options.yaml
    ports:
      - 8412:8412
    networks:
      - fleet-preview

